#define FOLDER_VOLUME_GOOD 1
#define FOLDER_VOLUME_HIGHER 2
#define FOLDER_FREQUENCY_GOOD 3
#define FOLDER_FREQUENCY_LOWER 4
#define FOLDER_VOLUME_ON_LED 5
#define FOLDER_FREQUENCY_ON_LED 6
#define FOLDER_RELAX 7
#define FOLDER_MUTE 8

#define VOLUME_GOOD_FILES_AMOUNT 2
#define VOLUME_HIGHER_FILES_AMOUNT 2
#define FREQUENCY_GOOD_FILES_AMOUNT 2
#define FREQUENCY_LOWER_FILES_AMOUNT 2
#define VOLUME_ON_LED_FILES_AMOUNT 1
#define FREQUENCY_ON_LED_FILES_AMOUNT 1
#define RELAX_FILES_AMOUNT 1

#define MUTE_FILE_MUTED 1
#define MUTE_FILE_UNMUTED 2
